### ISSUE TITLE
latest chrome breaks project sand

### ISSUE THREAD

**Issue by qpwo** [joshdon/ProjectSand#2]
Running latest chrome and latest macos nothing is rendered

![image](https://user-images.githubusercontent.com/10591373/134938907-0edafb99-2774-4d82-aa51-d415c8ab3b96.png)

https://www.projectsand.io/

**Comment by qpwo** [comment]
Break appears to occur between chrome 92.0 and 94.0

**Comment by joshdon** [comment]
Thanks for the report. I've confirmed it repro's on my end on chrome 94.0.

**Comment by joshdon** [comment]
Fixed in 5eb6ae4aaad. As far as I can tell there's a bug in either Chrome or Mac OS. Sever should be updated shortly.

**Comment by qpwo** [comment]
It was  chrome pretty sure. Have 92 and 94 installed and 92 was working
