### ISSUE TITLE
Add WAY/LOTS more stuff to it. Make the biggest update ever!!!

### ISSUE THREAD

**Issue by projectguy100** [joshdon/ProjectSand#7]
you havent updates it in a long time so....

**Comment by projectguy100** [comment]
I really love your work and I have been playing it for so long. I was wondering if you take pull requests and updating it rn?

**Comment by projectguy100** [comment]
@joshdon helooooo???>??

**Comment by joshdon** [comment]
Hi,

Yes I'm open to pull requests for limited additions.

FWIW a more productive request for new changes would look more like https://github.com/joshdon/ProjectSand/issues/6
